apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: "{{ .Values.backend.image }}:{{ .Values.backend.tag }}"
        ports:
        - containerPort: {{ .Values.backend.port }}
        env:
        - name: ATLAS_URI
          value: "{{ .Values.backend.env.ATLAS_URI }}"
        - name: HASH_KEY
          value: "{{ .Values.backend.env.HASH_KEY }}"
        - name: JWT_SECRET_KEY
          value: "{{ .Values.backend.env.JWT_SECRET_KEY }}"
