apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  selector:
    app: mongo
  ports:
  - protocol: TCP
    port: {{ .Values.mongo.service.port }}
    targetPort: {{ .Values.mongo.service.port }}
  type: ClusterIP
